.MODEL SMALL
.STACK 100H

; ============= MACRO DEFINITIONS =============

; Macro to display a string
DISPLAY_STRING MACRO STRING
    LEA DX,STRING
    MOV AH,9
    INT 21H
ENDM

; Macro to display newline
NEWLINE MACRO
    DISPLAY_STRING NL
ENDM

; Macro to get single character input
GET_CHAR MACRO
    MOV AH,1
    INT 21H
ENDM

; Macro for exit program
EXIT_PROGRAM MACRO
    MOV AH,4CH
    INT 21H
ENDM

; Macro to check if account exists
CHECK_ACCOUNT_EXISTS MACRO
    MOV AX,BALANCE
    CMP AX,0
    JE NO_ACC
ENDM

; Macro to verify PIN
VERIFY_PIN MACRO
    DISPLAY_STRING ENTER_PIN_MSG
    CALL READ_AMOUNT
    MOV ENTERED_PIN,AX
    
    MOV AX,PIN
    CMP AX,ENTERED_PIN
    JNE WRONG_PIN
ENDM

; Macro to show balance
SHOW_BALANCE MACRO
    DISPLAY_STRING NEW_BAL_MSG
    MOV AX,BALANCE
    CALL PRINT_NUM
    NEWLINE
ENDM

; ============= DATA SECTION =============

.DATA
HEADING     DB '*****BANKING SIMULATION*****',10,13,'$'
MENU_TITLE  DB 'MAIN MENU',10,13,'$'
OPTION1     DB '1. CREATE NEW ACCOUNT',10,13,'$'
OPTION2     DB '2. DEPOSIT MONEY',10,13,'$'
OPTION3     DB '3. WITHDRAW MONEY',10,13,'$'
OPTION4     DB '4. CHECK BALANCE',10,13,'$'
OPTION5     DB '5. TRANSFER MONEY',10,13,'$'
OPTION6     DB '6. EXIT',10,13,'$'
CHOICE_MSG  DB 'ENTER YOUR CHOICE: $'

ACC_NUM_MSG DB 'YOUR ACCOUNT NUMBER IS: $'
INIT_DEP_MSG DB 'ENTER INITIAL DEPOSIT (MIN 500): $'
DEPOSIT_MSG DB 'ENTER DEPOSIT AMOUNT: $'
WITHDRAW_MSG DB 'ENTER WITHDRAW AMOUNT: $'
BALANCE_MSG DB 'YOUR BALANCE IS: $'
NEW_BAL_MSG DB 'NEW BALANCE: $'
TRANSFER_MSG DB 'ENTER AMOUNT TO TRANSFER: $'
TO_ACC_MSG  DB 'ENTER RECEIVER ACCOUNT NUMBER: $'
TRANSFER_SUCCESS DB 'TRANSFER SUCCESSFUL!',10,13,'$'
TRANSFER_FAIL DB 'TRANSFER FAILED!',10,13,'$'

SUCCESS_MSG DB 'OPERATION SUCCESSFUL!',10,13,'$'
ACC_CREATED DB 'SUCCESSFUL ACCOUNT CREATED!',10,13,'$'
INSUFFICIENT DB 'INSUFFICIENT BALANCE!',10,13,'$'
INVALID_MSG DB 'INVALID! TRY AGAIN.',10,13,'$'
MIN_BAL_MSG DB 'MINIMUM 500 REQUIRED!',10,13,'$'
THANK_MSG   DB 'THANK YOU!',10,13,'$'

PIN_MSG       DB 'SET YOUR 4-DIGIT PIN: $'
ENTER_PIN_MSG DB 'ENTER YOUR PIN: $'
WRONG_PIN_MSG DB 'WRONG PIN!',10,13,'$'

PIN          DW 0
ENTERED_PIN  DW 0

NL          DB 10,13,'$'

ACC_NUMBER  DW 100
BALANCE     DW 0
AMOUNT      DW 0
TEMP        DW 0
MIN_BAL     DW 500

; For transfer
RECEIVER_ACC1 DW 1001
RECEIVER_BAL1 DW 2000

; ============= CODE SECTION =============

.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX

; ============= MAIN MENU =============
START: 
    ; Display main menu
    DISPLAY_STRING HEADING
    NEWLINE
    DISPLAY_STRING MENU_TITLE
    
    ; Display menu options
    DISPLAY_STRING OPTION1
    DISPLAY_STRING OPTION2
    DISPLAY_STRING OPTION3
    DISPLAY_STRING OPTION4
    DISPLAY_STRING OPTION5
    DISPLAY_STRING OPTION6
    NEWLINE
    
    ; Get user choice
    DISPLAY_STRING CHOICE_MSG
    GET_CHAR
    
    ; Process user choice
    CMP AL,'1'
    JE CREATE_ACC
    CMP AL,'2'
    JE DEPOSIT
    CMP AL,'3'
    JE WITHDRAW
    CMP AL,'4'
    JE CHECK_BAL
    CMP AL,'5'
    JE TRANSFER_MONEY
    CMP AL,'6'
    JE EXIT_PROG
    JMP INVALID

; ============= CREATE ACCOUNT =============
CREATE_ACC:
    NEWLINE
    DISPLAY_STRING ACC_NUM_MSG
    
    ; Generate and display account number
    MOV AX,ACC_NUMBER
    CALL PRINT_NUM
    INC ACC_NUMBER
    
    NEWLINE
    
    ; Set PIN
    DISPLAY_STRING PIN_MSG
    CALL READ_AMOUNT
    MOV PIN,AX
    
    NEWLINE
    
    ; Get initial deposit
    DISPLAY_STRING INIT_DEP_MSG
    CALL READ_AMOUNT
    MOV AMOUNT,AX
    
    ; Check minimum balance
    CMP AX,MIN_BAL
    JL MIN_ERROR
    
    MOV BALANCE,AX
    
    NEWLINE
    DISPLAY_STRING ACC_CREATED
    JMP START

MIN_ERROR:
    NEWLINE
    DISPLAY_STRING MIN_BAL_MSG
    JMP CREATE_ACC

; ============= DEPOSIT MONEY =============
DEPOSIT:
    NEWLINE
    CHECK_ACCOUNT_EXISTS
    
    DISPLAY_STRING DEPOSIT_MSG
    CALL READ_AMOUNT
    MOV AMOUNT,AX
    
    CMP AX,0
    JLE INVALID_AMT
    
    NEWLINE
    VERIFY_PIN
    
    ; Perform deposit
    MOV AX,AMOUNT
    ADD BALANCE,AX
    
    NEWLINE
    DISPLAY_STRING SUCCESS_MSG
    SHOW_BALANCE
    JMP START

; ============= WITHDRAW MONEY =============
WITHDRAW:
    NEWLINE
    CHECK_ACCOUNT_EXISTS
    
    DISPLAY_STRING WITHDRAW_MSG
    CALL READ_AMOUNT
    MOV AMOUNT,AX
    
    CMP AX,0
    JLE INVALID_AMT
    
    ; Check sufficient balance
    MOV BX,BALANCE
    CMP AX,BX
    JG INSUFF
    
    NEWLINE
    VERIFY_PIN
    
    ; Perform withdrawal
    MOV AX,AMOUNT
    SUB BX,AX
    MOV BALANCE,BX
    
    NEWLINE
    DISPLAY_STRING SUCCESS_MSG
    SHOW_BALANCE
    JMP START

; ============= TRANSFER MONEY =============
TRANSFER_MONEY:
    NEWLINE
    CHECK_ACCOUNT_EXISTS
    
    ; Get receiver account number
    DISPLAY_STRING TO_ACC_MSG
    CALL READ_AMOUNT
    MOV TEMP,AX
    
    NEWLINE
    
    ; Get transfer amount
    DISPLAY_STRING TRANSFER_MSG
    CALL READ_AMOUNT
    MOV AMOUNT,AX
    
    CMP AX,0
    JLE TRANSFER_ERROR
    
    ; Check sufficient balance
    MOV BX,BALANCE
    CMP AX,BX
    JG TRANSFER_ERROR
    
    ; Check receiver account exists
    MOV AX,TEMP
    CMP AX,RECEIVER_ACC1
    JNE TRANSFER_ERROR
    
    NEWLINE
    VERIFY_PIN
    
    ; Perform transfer
    MOV AX,AMOUNT
    SUB BALANCE,AX
    ADD RECEIVER_BAL1,AX
    
    NEWLINE
    DISPLAY_STRING TRANSFER_SUCCESS
    SHOW_BALANCE
    JMP START

; ============= CHECK BALANCE =============
CHECK_BAL:
    NEWLINE
    CHECK_ACCOUNT_EXISTS
    
    ; Show PIN message and read PIN
    DISPLAY_STRING ENTER_PIN_MSG
    CALL READ_AMOUNT
    MOV ENTERED_PIN,AX
    
    MOV AX,PIN
    CMP AX,ENTERED_PIN
    JNE WRONG_PIN_BAL
    
    ; Show balance
    DISPLAY_STRING BALANCE_MSG
    MOV AX,BALANCE
    CALL PRINT_NUM
    NEWLINE
    
    JMP START

; ============= ERROR HANDLERS =============
INSUFF:
    NEWLINE
    DISPLAY_STRING INSUFFICIENT
    JMP START

WRONG_PIN:
    NEWLINE
    DISPLAY_STRING WRONG_PIN_MSG
    JMP START

NO_ACC:
    NEWLINE
    DISPLAY_STRING INVALID_MSG
    JMP START

INVALID_AMT:
    NEWLINE
    DISPLAY_STRING INVALID_MSG
    JMP START

TRANSFER_ERROR:
    NEWLINE
    DISPLAY_STRING TRANSFER_FAIL
    JMP START

NO_ACC_BAL:
    NEWLINE
    DISPLAY_STRING INVALID_MSG
    JMP START

WRONG_PIN_BAL:
    NEWLINE
    DISPLAY_STRING WRONG_PIN_MSG
    JMP START

INVALID:
    NEWLINE
    DISPLAY_STRING INVALID_MSG
    JMP START

; ============= EXIT PROGRAM =============
EXIT_PROG:
    NEWLINE
    DISPLAY_STRING THANK_MSG
    EXIT_PROGRAM

; ============= PROCEDURES =============

; Procedure to print a number
PRINT_NUM PROC
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX

    MOV CX,0
    MOV BX,10

    CMP AX,0
    JNE CONVERT_LOOP
    MOV DL,'0'
    MOV AH,2
    INT 21H
    JMP PRINT_DONE

CONVERT_LOOP:
    MOV DX,0
    DIV BX
    PUSH DX
    INC CX
    CMP AX,0
    JNE CONVERT_LOOP

PRINT_LOOP:
    POP DX
    ADD DL,'0'
    MOV AH,2
    INT 21H
    LOOP PRINT_LOOP

PRINT_DONE:
    POP DX
    POP CX
    POP BX
    POP AX
    RET
PRINT_NUM ENDP

; Procedure to read an amount/number
READ_AMOUNT PROC
    PUSH BX
    PUSH CX
    PUSH DX
    
    MOV BX,0
    
READ_CHAR:
    MOV AH,1
    INT 21H
    
    CMP AL,13
    JE DONE_READ
    
    CMP AL,'0'
    JB DONE_READ
    CMP AL,'9'
    JA DONE_READ
    
    SUB AL,'0'
    MOV AH,0
    
    PUSH AX
    MOV AX,BX
    MOV CX,10
    MUL CX
    MOV BX,AX
    POP AX
    
    ADD BX,AX
    JMP READ_CHAR
    
DONE_READ:
    MOV AX,BX
    
    POP DX
    POP CX
    POP BX
    RET
READ_AMOUNT ENDP

END MAIN